//src\infrastructure\sheets\SheetKey.ts
export const SheetKey = {
  BOM_MATRIX_COLUMNS: 'BOM_MATRIX_COLUMNS',
  CATALOG: 'CATALOG',
  MATERIAL_BATCHES: 'MATERIAL_BATCHES',
  MATERIALS: 'MATERIALS',
  PLACEMENT: 'PLACEMENT',
  SHIFT_PLAN: 'SHIFT_PLAN',
  SHIFT_PLAN_ITEMS: 'SHIFT_PLAN_ITEMS',
  PRODUCTION: 'PRODUCTION',
  PROJECTS: 'PROJECTS',
  PROJECT_DOCUMENTS: 'PROJECT_DOCUMENTS', //'19_ProjectDocuments',
  HOUSES: 'HOUSES', //'20_Houses',
  PROJECT_DOCUMENT_DEPENDENCIES: 'PROJECT_DOCUMENT_DEPENDENCIES', //'21_ProjectDocumentDependencies'
  REPORT_MATERIAL_MATRIX: 'REPORT_MATERIAL_MATRIX',
  MANUFACTURING: 'MANUFACTURING',
} as const;

export type SheetKey = (typeof SheetKey)[keyof typeof SheetKey];
